/**
 * Used to model a Stock Quote that we get back from 
 * https://api.iextrading.com/1.0/stock/${ticker}/quote
 */
export class StockQuote {
  symbol:string;
  companyName:string;
  primaryExchange:string;
  sector:string;
  calculationPrice:string;
  open:number;
  openTime:number;
  close:number;
  closeTime:number;
  high:number;
  low:number;
  latestPrice:number;
  latestSource:string;
  latestTime:string;
  latestUpdate:number;
  latestVolume:number;
  iexRealtimePrice:number;
  iexRealtimeSize:number;
  iexLastUpdated:number;
  delayedPrice:number;
  delayedPriceTime:number;
  extendedPrice:number;
  extendedChange:number;
  extendedChangePercent:number;
  extendedPriceTime:number;
  previousClose:number;
  change:number;
  changePercent:number;
  iexMarketPercent:number;
  iexVolume:number;
  avgTotalVolume:number;
  iexBidPrice:number;
  iexBidSize:number;
  iexAskPrice:number;
  iexAskSize:number;
  marketCap:number;
  peRatio:number;
  week52High:number;
  week52Low:number;
  ytdChange:number;
}